{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.biometric",
    "module": "biometric",
    "version": "1.2.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "biometric-1.2.0-alpha04.aar",
          "url": "biometric-1.2.0-alpha04.aar",
          "size": 241380,
          "sha512": "4b28f51ad5757708d6bbf2f9d8bccfc4d921ac13bed899324e6cc8f2a0051e20f3ca145bfe3ef3e7fae502f6ac97880e11511ff6eaaba4b550efba36265ce7de",
          "sha256": "ebcd741bded2cfc4dbb12aa00b7fd575ef440e6047dd41c002ba2bf604eb700d",
          "sha1": "554e724705968b1967c78d676662bf7cdbebcc0e",
          "md5": "02fc5964794778c55487262a0e2326c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "biometric-1.2.0-alpha04.aar",
          "url": "biometric-1.2.0-alpha04.aar",
          "size": 241380,
          "sha512": "4b28f51ad5757708d6bbf2f9d8bccfc4d921ac13bed899324e6cc8f2a0051e20f3ca145bfe3ef3e7fae502f6ac97880e11511ff6eaaba4b550efba36265ce7de",
          "sha256": "ebcd741bded2cfc4dbb12aa00b7fd575ef440e6047dd41c002ba2bf604eb700d",
          "sha1": "554e724705968b1967c78d676662bf7cdbebcc0e",
          "md5": "02fc5964794778c55487262a0e2326c0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "biometric-1.2.0-alpha04-sources.jar",
          "url": "biometric-1.2.0-alpha04-sources.jar",
          "size": 70274,
          "sha512": "24352d6af263fd0bd8e607c8b636e2942b758bf4540e4e76cf3230d34cc2d016b31a732c2ffc4f18383757fe9c00ea1572462dba5870e904491e7efa2dbcc3db",
          "sha256": "1270b6c68648c79d363ccad25a1887ad04406cbd587d456291024d385e291aad",
          "sha1": "6549f5166042771d6bef6e4c0f235de1f1fd34c9",
          "md5": "1e405c68e3e40a8300c88981a887fa8d"
        }
      ]
    }
  ]
}
