{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-runtime",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId:": "7085123"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "work-runtime-2.5.0.aar",
          "url": "work-runtime-2.5.0.aar",
          "size": 1541328,
          "sha512": "4aca4cc3743723f5e9d3cd189f6561e8a7784e839e4434512bb1873c2b11f976ce8c3e956938e4c62eaefa9292e860f697124983222e8e026a6ce64f289ea588",
          "sha256": "59cdbf1311e901650b17b8414f1e2a9443813a099d3c58fe9ba0ae6a00bed18f",
          "sha1": "b878e75e14ee7e745fe120bc78e8db8995064f4d",
          "md5": "d80b9497922bacd71fb12793398d8c9d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.5"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "work-runtime-2.5.0.aar",
          "url": "work-runtime-2.5.0.aar",
          "size": 1541328,
          "sha512": "4aca4cc3743723f5e9d3cd189f6561e8a7784e839e4434512bb1873c2b11f976ce8c3e956938e4c62eaefa9292e860f697124983222e8e026a6ce64f289ea588",
          "sha256": "59cdbf1311e901650b17b8414f1e2a9443813a099d3c58fe9ba0ae6a00bed18f",
          "sha1": "b878e75e14ee7e745fe120bc78e8db8995064f4d",
          "md5": "d80b9497922bacd71fb12793398d8c9d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "work-runtime-2.5.0-sources.jar",
          "url": "work-runtime-2.5.0-sources.jar",
          "size": 259948,
          "sha512": "f5d950c8dacfe4bac635b1b3b578bcbab4cd5ff51475c3b37fcb9b10de8591581588c9e3f8e43e63b1381030fc02bf066fc80d118b701b140dcace0d70a9325e",
          "sha256": "d3771c6e90408aa34074cb6ac5c79edbb9f19284779d220c8719ed57f11bc55e",
          "sha1": "f0a35272321dcf8f72108a971adcf3891e90b75f",
          "md5": "91983f0fe8ddaa53af3c44c923365946"
        }
      ]
    }
  ]
}
