{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "viewbinding",
    "version": "7.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-7.1.1.aar",
          "url": "viewbinding-7.1.1.aar",
          "size": 2560,
          "sha512": "b81c648860dbb1dafac736ec6fe982c7a7e368557c485e2e735df4c11c254b64d697ab1d5db68f21719aba4f3c425ba271b4580f86fd8068ed6c42f034612b7b",
          "sha256": "a44c74f1f916facc0b39da3ce95fd6fc436f8307991e2e76f82b0f5086fb0abd",
          "sha1": "cc09b0c0673f4c1a93c52ad5b0700434b3b1e077",
          "md5": "f86669fc63d3f49254aefdd858095149"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-7.1.1.aar",
          "url": "viewbinding-7.1.1.aar",
          "size": 2560,
          "sha512": "b81c648860dbb1dafac736ec6fe982c7a7e368557c485e2e735df4c11c254b64d697ab1d5db68f21719aba4f3c425ba271b4580f86fd8068ed6c42f034612b7b",
          "sha256": "a44c74f1f916facc0b39da3ce95fd6fc436f8307991e2e76f82b0f5086fb0abd",
          "sha1": "cc09b0c0673f4c1a93c52ad5b0700434b3b1e077",
          "md5": "f86669fc63d3f49254aefdd858095149"
        }
      ]
    }
  ]
}
