{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nikartm",
    "module": "image-support",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "image-support-2.0.0.aar",
          "url": "image-support-2.0.0.aar",
          "size": 25992,
          "sha512": "6e4b765b5f73258f0a1e9a5c4b82cc2444ff2273b3c4a1af85b610512a099dd3afb680920d98587789d428eaba319408a310a938b21058efd1550a19700a0fc0",
          "sha256": "e300649a9a1f5d7614f55c734dd5c52b0ebe2660f2485a0cee2fdc8985a26858",
          "sha1": "4b9b9f98499cba3af17d5811eaea4576e6833a6e",
          "md5": "f082d92150c4d91d3f2a2d0fb3b41ef7"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "image-support-2.0.0.aar",
          "url": "image-support-2.0.0.aar",
          "size": 25992,
          "sha512": "6e4b765b5f73258f0a1e9a5c4b82cc2444ff2273b3c4a1af85b610512a099dd3afb680920d98587789d428eaba319408a310a938b21058efd1550a19700a0fc0",
          "sha256": "e300649a9a1f5d7614f55c734dd5c52b0ebe2660f2485a0cee2fdc8985a26858",
          "sha1": "4b9b9f98499cba3af17d5811eaea4576e6833a6e",
          "md5": "f082d92150c4d91d3f2a2d0fb3b41ef7"
        }
      ]
    }
  ]
}
